
namespace HavenUI;

public static class VTColor
{
	public const byte Black = 0;
	public const byte DarkRed = 1;
	public const byte DarkGreen = 2;
	public const byte DarkYellow = 3;
	public const byte DarkBlue = 4;
	public const byte DarkMagenta = 5;
	public const byte DarkCyan = 6;
	public const byte DarkGray = 7;
	public const byte Gray = 8;
	public const byte Cyan = 14;
	public const byte White = 15;

	public const byte AbyssalBlue = 17;
	public const byte MidnightinTokyo = 18;
	public const byte TraditionalRoyalBlue = 19;
	public const byte Bluealicious = 20;
	public const byte Blue = 21;
	public const byte EmeraldGreen = 22;
	public const byte SandhillCrane = 23;
	public const byte BlueFlame = 24;
	public const byte GreekFlagBlue = 25;
	public const byte BneiBrakBay = 26;
	public const byte Y7KBlue = 27;
	public const byte FinePine = 28;
	public const byte PrimalGreen = 29;
	public const byte GreenMoblin = 30;
	public const byte StomyShower = 31;
	public const byte BlueCola = 32;
	public const byte TooBlueToBeTrue = 33;
	public const byte PikkoroGreen = 34;
	public const byte NordicGrassGreen = 35;
	public const byte ChromophobiaGreen = 36;
	public const byte GreenlandGreen = 37;
	public const byte BatteryChargedBlue = 38;
	public const byte KrishnaBlue = 39;
	public const byte GreenWrasse = 40;
	public const byte Limonana = 41;
	public const byte ReptileGreen = 42;
	public const byte ChannelMarkerGreen = 43;
	public const byte FishBoy = 44;
	public const byte NeonBlue = 45;
	public const byte Green = 46;
	public const byte CathodeGreen = 47;
	public const byte GuppieGreen = 48;
	public const byte Enthusiasm = 49;
	public const byte Aurichalcite = 50;
	public const byte SpikeyRed = 52;
	public const byte ClearPlum = 53;
	public const byte PeacefulPurple = 54;
	public const byte AuberginePerl = 55;
	public const byte SpaceOpera = 56;
	public const byte ElectricIndigo = 57;
	public const byte EarthyKhakiGreen = 58;
	public const byte Iron = 59;
	public const byte PharaohPurple = 60;
	public const byte YuèGuāngLánMoonlight = 61;
	public const byte DarkPeriwinkle = 62;
	public const byte BlueGenie = 63;
	public const byte PestoAllaGenovese = 64;
	public const byte MagicSage = 65;
	public const byte SteelTeal = 66;
	public const byte LichenBlue = 67;
	public const byte Livid = 68;
	public const byte DeepDenim = 69;
	public const byte KermitGreen = 70;
	public const byte BoringGreen = 71;
	public const byte VerdigrisGreen = 72;
	public const byte EmeraldSucculent = 73;
	public const byte ImrikBlue = 74;
	public const byte JoustBlue = 75;
	public const byte CorrosiveGreen = 76;
	public const byte KoopaGreenShell = 77;
	public const byte SpringBouquet = 78;
	public const byte OceaninaBowl = 79;
	public const byte Pluviophile = 80;
	public const byte LibraBlueMorpho = 81;
	public const byte BrightLimeGreen = 82;
	public const byte GreenKatamari = 83;
	public const byte GuppieGreen2 = 84;
	public const byte HanumanGreen = 85;
	public const byte Spindrift = 86;
	public const byte MoongladeWater = 87;
	public const byte Chanticleer = 88;
	public const byte CardinalPink = 89;
	public const byte MardiGras = 90;
	public const byte ShadeofViolet = 91;
	public const byte FrenchViolet = 92;
	public const byte PurpleClimax = 93;
	public const byte RatBrown = 94;
	public const byte Tarsier = 95;
	public const byte DustyPurple = 96;
	public const byte LustyLavender = 97;
	public const byte GloomyPurple = 98;
	public const byte PurpleAnemone = 99;
	public const byte PalakPaneer = 100;
	public const byte GreenSavage = 101;
	public const byte Mithril = 102;
	public const byte SweetLavender = 103;
	public const byte Perrywinkle = 104;
	public const byte LavenderBlueShadow = 105;
	public const byte GameboyScreen = 106;
	public const byte Broccoli = 107;
	public const byte ShadedWillow = 108;
	public const byte Hydrology = 109;
	public const byte BlueBell = 110;
	public const byte KittensEye = 111;
	public const byte Frogger = 112;
	public const byte LilliputianLime = 113;
	public const byte ElectricLettuce = 114;
	public const byte PharaohsJade = 115;
	public const byte IslandOasis = 116;
	public const byte KulSharifBlue = 117;
	public const byte LastingLime = 118;
	public const byte PoisonousDart = 119;
	public const byte EasterGreen = 120;
	public const byte EspersFungusGreen = 121;
	public const byte HiroshimaAquamarine = 122;
	public const byte GlitterShower = 123;
	public const byte RedDoor = 124;
	public const byte BanafsajiPurple = 125;
	public const byte BlissfulBerry = 126;
	public const byte EnergicEggplant = 127;
	public const byte VibrantPurple = 128;
	public const byte BrightViolet = 129;
	public const byte OrangeBrown = 130;
	public const byte ItalianVilla = 131;
	public const byte WildMulberry = 132;
	public const byte RoyaltyLoyalty = 133;
	public const byte TeldrassilPurple = 134;
	public const byte PurpleHedonist = 135;
	public const byte ChestnutGold = 136;
	public const byte LightOakBrown = 137;
	public const byte Woodrose = 138;
	public const byte DustyLavender = 139;
	public const byte MiddysPurple = 140;
	public const byte LilacGeode = 141;
	public const byte HoneyandThyme = 142;
	public const byte Palm = 143;
	public const byte NewBamboo = 144;
	public const byte SmokeScreen = 145;
	public const byte FreesiaPurple = 146;
	public const byte ShyMoment = 147;
	public const byte KingLime = 148;
	public const byte LimeLizard = 149;
	public const byte PeasInAPod = 150;
	public const byte FlowerStem = 151;
	public const byte SugarPool = 152;
	public const byte MalmöFF = 153;
	public const byte LimeAcid = 154;
	public const byte PaleLimeGreen = 155;
	public const byte Lima = 156;
	public const byte CreamyMint = 157;
	public const byte Mintastic = 158;
	public const byte Celeste = 159;
	public const byte RedRepublic = 160;
	public const byte LovePotion = 161;
	public const byte TheArtofSeduction = 162;
	public const byte PerfectlyPurplePlace = 163;
	public const byte FúchsiaIntenso = 164;
	public const byte PsychedelicPurple = 165;
	public const byte AncientBamboo = 166;
	public const byte HappyHearts = 167;
	public const byte BlushdAmour = 168;
	public const byte PúTáoZǐPurple = 169;
	public const byte FreeSpeechMagenta = 170;
	public const byte FlamingFlamingo = 171;
	public const byte FleurdeSelCaramel = 172;
	public const byte CopperWire = 173;
	public const byte PeachesofImmortality = 174;
	public const byte HighMaintenance = 175;
	public const byte LavenderPink = 176;
	public const byte LavenderTea = 177;
	public const byte PalominoGold = 178;
	public const byte Equator = 179;
	public const byte SantaFeTan = 180;
	public const byte RadiantRouge = 181;
	public const byte WhisperofPlum = 182;
	public const byte LightViolet = 183;
	public const byte SulphurSpring = 184;
	public const byte BananaChalk = 185;
	public const byte WaxGreen = 186;
	public const byte KohlrabiGreen = 187;
	public const byte SilverMedal = 188;
	public const byte TransparentBlue = 189;
	public const byte LimeZest = 190;
	public const byte GreenofBhabua = 191;
	public const byte HoneydewPeel = 192;
	public const byte LimeMist = 193;
	public const byte TransparentGreen = 194;
	public const byte SaltMountain = 195;
	public const byte Red = 196;
	public const byte FlamingHotFlamingoes = 197;
	public const byte FancyFuchsia = 198;
	public const byte MeanGirlsLipstick = 199;
	public const byte CupidsEye = 200;
	public const byte Magenta = 201;
	public const byte VividOrange = 202;
	public const byte FusionRed = 203;
	public const byte WarmPink = 204;
	public const byte PinkKatydid = 205;
	public const byte IllicitPink = 206;
	public const byte VioletPink = 207;
	public const byte MandarinJelly = 208;
	public const byte PinkFire = 209;
	public const byte RedMull = 210;
	public const byte InformativePink = 211;
	public const byte PinkDelight = 212;
	public const byte DarlingBud = 213;
	public const byte TurmericRoot = 214;
	public const byte VintageOrange = 215;
	public const byte SpicePink = 216;
	public const byte FancyFlamingo = 217;
	public const byte SpaghettiStrapPink = 218;
	public const byte Jigglypuff = 219;
	public const byte Gold = 220;
	public const byte AspenGold = 221;
	public const byte WorkoutRoutine = 222;
	public const byte DeliciousMelon = 223;
	public const byte WePeep = 224;
	public const byte PinkDiamond = 225;
	public const byte Yellow = 226;
	public const byte CandyCorn = 227;
	public const byte CinqueFoil = 228;
	public const byte VIC20Creme = 229;
	public const byte PoeticYellow = 230;
	public const byte ReversedGray = 232;
	public const byte DarkToneInk = 233;
	public const byte EerieBlack = 234;
	public const byte Nero = 235;
	public const byte OffBlack = 236;
	public const byte BoltgunMetal = 237;
	public const byte GoshawkGray = 238;
	public const byte FiftiethShadeOfGray = 239;
	public const byte ShadowMountain = 240;
	public const byte Kettleman = 241;
	public const byte DoveGray = 242;
	public const byte LuckyGray = 243;
	public const byte Argent = 245;
	public const byte Nickel = 246;
	public const byte ColdGray = 247;
	public const byte UniformGray = 248;
	public const byte TangledWeb = 249;
	public const byte GravelFint = 250;
	public const byte SilverPolish = 251;
	public const byte AncestralWater = 252;
	public const byte Gainsboro = 253;
	public const byte TitaniumWhite = 254;
	public const byte SuperSilver = 255;
}


public static class ColorExtexnsions
{
#pragma warning disable CS8524
	public static byte ToByte(this ConsoleColor Color) => Color switch
	{
		ConsoleColor.Black => 0,
		ConsoleColor.Red => 9,
		ConsoleColor.Green => 10,
		ConsoleColor.Yellow => 11,
		ConsoleColor.Blue => 12,
		ConsoleColor.Magenta => 13,
		ConsoleColor.Cyan => 14,
		ConsoleColor.White => 15,
		ConsoleColor.DarkRed => 1,
		ConsoleColor.DarkGreen => 2,
		ConsoleColor.DarkYellow => 3,
		ConsoleColor.DarkBlue => 4,
		ConsoleColor.DarkMagenta => 5,
		ConsoleColor.DarkCyan => 6,
		ConsoleColor.Gray => 7,
		ConsoleColor.DarkGray => 8
	};
#pragma warning restore CS8524
}